[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = "7"
async-graphql-axum = "7"
axum = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "macros"] }
cuid2 = "0.1"
tower-http = { version = "0.5", features = ["cors"] }
url = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasmtime = "21"
wasmtime-wasi = "21"
wasi-common = "21"