[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = "7"
async-graphql-axum = "7"
axum = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tokio-util = "0.7"
anyhow = "1"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "macros"] }
cuid2 = "0.1"
tower-http = { version = "0.5", features = ["cors"] }
url = "2"
gix = { version = "0.73.0", features = ["blocking-http-transport-reqwest-rust-tls"] }
wasmtime = "26"
wasmtime-wasi = "26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
async-graphql-parser = "7"
metrics = "0.23"

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.0"
