[package]
name = "forgepoint-extension-issues"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.37"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
wit-bindgen = "0.37"