name: Copilot Environment Setup

on:
  workflow_dispatch:
    inputs:
      runner_os:
        description: 'Operating System'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - ubuntu-latest
        - macos-latest

jobs:
  setup-nix:
    runs-on: ${{ github.event.inputs.runner_os || 'ubuntu-latest' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        logger: pretty
    
    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    
    - name: Verify Nix installation
      run: |
        nix --version
        echo "✅ Nix installed successfully"
        echo ""
        echo "Next steps for Copilot environment:"
        echo "1. Enter development environment: nix develop"
        echo "2. All tools (Rust, Bun, formatters) will be available automatically"
        echo ""
        echo "See .github/copilot-instructions.md for detailed development information."